function KatieOlfactometer_20141218
% GUI for imaging experiment with odor delivery as well as shock delivery.
% Adapted from DHImaging_plusShock_v141014
handles.DIO = digitalio('mcc',0); % Add DigitalIO Adaptor for Olf
addline(handles.DIO,0:7,'out'); % Add hardware lines 

handles.olf = SimpleOlfClient('156.111.46.102');  % Open Olf (Need its IP)
% General form of commands to olfactometer: 
% Write('olfactometer', 'bank', 'valve')
% For example, to change to valve 1 on bank v3:
% Write(olf, 'b3v', 1) 
% Note that banks are referred to as e.g. b2v, b3v on the 9th floor's
% olfactometer.

handles.MFC3Flow = 0;
handles.MFC2Flow = 0;
handles.Bank3Valve = 0;

% Set up figure for GUI 
handles.hFig1 = figure('pos',[1022 33 416 465]);
handles.hEdit1 = uicontrol(handles.hFig1,...
                    'Style','edit',...
                    'Units','normalized',...
                    'Position',[0.2 0.8 0.2 0.05],...
                    'String','Carrier',...
                    'Callback',{@Callback_hEdit1_Carrier});
handles.hEdit2 = uicontrol(handles.hFig1,...
                    'Style','edit',...
                    'Units','normalized',...
                    'Position',[0.6 0.8 0.2 0.05],...
                    'String','Odor',...
                    'Callback',{@Callback_hEdit2_Odor});
handles.hText1 = uicontrol(handles.hFig1,...
                    'Style','text',...
                    'Units','normalized',...
                    'Position',[0.2 0.9 0.2 0.05],...
                    'String','Carrier(MFC3)');
handles.hText2 = uicontrol(handles.hFig1,...
                    'Style','text',...
                    'Units','normalized',...
                    'Position',[0.6 0.9 0.2 0.05],...
                    'String','Odor(MFC2)');
handles.hText3 = uicontrol(handles.hFig1,...
                    'Style','text',...
                    'Units','normalized',...
                    'Position',[0.4 0.7 0.2 0.05],...
                    'String','Bank V3');
handles.hText4 = uicontrol(handles.hFig1,...
                    'Style','text',...
                    'Units','normalized',...
                    'Position',[0.6 0.175 0.2 0.05],...
                    'String','CurrentValve=0');
handles.hText5 = uicontrol(handles.hFig1,...
                    'Style','text',...
                    'Units','normalized',...
                    'Position',[0.6 0.125 0.2 0.05],...
                    'String','PreviousOdor=');
handles.hPush1 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.2 0.6 0.2 0.05],...
                    'String','Odor 1',...
                    'Callback',{@Callback_hPush_Valve,1});
handles.hPush2 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.2 0.45 0.2 0.05],...
                    'String','Odor 2',...
                    'Callback',{@Callback_hPush_Valve,2});
handles.hPush3 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.2 0.3 0.2 0.05],...
                    'String','Odor 3',...
                    'Callback',{@Callback_hPush_Valve,3});
handles.hPush4 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.2 0.15 0.2 0.05],...
                    'String','Odor 4',...
                    'Callback',{@Callback_hPush_Valve,4});
handles.hPush5 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.6 0.6 0.2 0.05],...
                    'String','Odor 5',...
                    'Callback',{@Callback_hPush_Valve,5});
handles.hPush6 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.6 0.45 0.2 0.05],...
                    'String','Odor 6',...
                    'Callback',{@Callback_hPush_Valve,6});
handles.hPush7 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.6 0.3 0.2 0.05],...
                    'String','Odor 7',...
                    'Callback',{@Callback_hPush_Valve,7});
handles.hEdit3 = uicontrol(handles.hFig1,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.45 0.05 0.05],...
    'String','3');
handles.hEdit4 = uicontrol(handles.hFig1,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.3 0.05 0.05],...
    'String','3');
handles.hText6 = uicontrol(handles.hFig1,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.5 0.05 0.05],...
    'String','Pre');
handles.hText7 = uicontrol(handles.hFig1,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.95 0.45 0.05 0.05],...
    'String','sec');
handles.hText8 = uicontrol(handles.hFig1,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.35 0.05 0.05],...
    'String','Stim');
handles.hText9 = uicontrol(handles.hFig1,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.95 0.3 0.05 0.05],...
    'String','sec');

handles.hPush11 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.8 0 0.2 0.05],...
                    'String','Clean Olf',...
                    'Callback',{@Callback_hPush_CleanOlf});
handles.hPush12 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0.2 0 0.2 0.05],...
                    'String','Shock only',...
                    'Callback',{@Callback_hPush_ShockOnly});                
handles.hToggle1 = uicontrol(handles.hFig1,...
                    'Style','toggle',...
                    'Units','normalized',...
                    'Position',[0.8 0.95 0.2 0.05],...
                    'String','Odor+Shock?',...
                    'ForegroundColor','k',...
                    'Callback',{@Callback_hToggle});                 
handles.hEdit6 = uicontrol(handles.hFig1,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.8 0.9 0.05 0.05],...
    'String','1.5');
handles.hText11 = uicontrol(handles.hFig1,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.85 0.9 0.15 0.05],...
    'String','sec after odor');                
handles.hPush13 = uicontrol(handles.hFig1,...
                    'Style','pushbutton',...
                    'Units','normalized',...
                    'Position',[0 0.95 0.2 0.05],...
                    'String','Make Rand Dir',...
                    'ForegroundColor','b',...
                    'Callback',{@Callback_hPush_RandDir});      

    function Callback_hEdit1_Carrier(hObject,eventdata)
        handles.MFC3Flow = str2double(get(handles.hEdit1,'String'));
        Write(handles.olf,'BankFlow3',handles.MFC3Flow);
    end

    function Callback_hEdit2_Odor(hObject,eventdata)
        handles.MFC2Flow = str2double(get(handles.hEdit2,'String'));
        Write(handles.olf,'BankFlow2',handles.MFC2Flow);
    end

    function Callback_hPush_Valve(hObject,eventdata,k)
        handles.Bank3Valve = k;
        bl=str2double(get(handles.hEdit3,'String'));
        stim = str2double(get(handles.hEdit4,'String'));
        if isequal(get(handles.hToggle1,'Value'),1)
            preshock = str2double(get(handles.hEdit6,'String'));
            postshock = stim-preshock;
            if postshock<=0
                errordlg('Odor duration must be longer than preshock period');
                return
            end
        end
        putvalue(handles.DIO,[1,0,0,0,0,0,0,0]);
        pause(bl);
        Write(handles.olf,'b3v',handles.Bank3Valve); % Change to Bank3Valve on bank b3v (Bank V3)
        set(handles.hText4,'String',strcat('CurrentValve=Bank3-',num2str(handles.Bank3Valve)));
        if isequal(get(handles.hToggle1,'Value'),1)
            pause(preshock);
            putvalue(handles.DIO,[1,0,1,0,0,0,0,0]);
            pause(postshock);
        else
            pause(stim);
        end
        Write(handles.olf,'b3v',0);
        putvalue(handles.DIO,[0,0,0,0,0,0,0,0]);
        set(handles.hText4,'String','CurrentValve=Bank3-0');
        set(handles.hText5,'String',strcat('PreviousOdor=',num2str(k)));
        c = clock;
        disp(['Odor #',num2str(k),' applied at ',num2str(c(4)),':',num2str(c(5)),':',num2str(c(6))]);
    end

    function Callback_hPush_ShockOnly(hObject,eventdata)
        % Shock only trial. Shock trigger is on the third line.
        bl=str2double(get(handles.hEdit3,'String'));
        % Shock duration is determined by the stimulator. So this 'stim' is
        % irrelevant.
        stim = str2double(get(handles.hEdit4,'String'));
        putvalue(handles.DIO,[1,0,0,0,0,0,0,0]);
        pause(bl);
        putvalue(handles.DIO,[1,0,1,0,0,0,0,0]);
        pause(stim);
        putvalue(handles.DIO,[0,0,0,0,0,0,0,0]);
    end
%     function Callback_hPush_Perfusion(hObject,eventdata)
%         ncycle = str2double(get(handles.hEdit5,'String'));
%         for n = 1:ncycle
%             putvalue(handles.DIO,[0,1,0,0,0,0,0,0]);
%             pause(0.25);
%             putvalue(handles.DIO,[0,0,0,0,0,0,0,0]);
%             pause(0.25);
%             n=n+1;
%         end
%     end
% 
%     function Callback_hPush_OpenPump(hObject,eventdata)
%         putvalue(handles.DIO,[0,1,0,0,0,0,0,0]);
%     end
% 
%     function Callback_hPush_ClosePump(hObject,eventdata)
%         putvalue(handles.DIO,[0,0,0,0,0,0,0,0]);
%     end

    function Callback_hPush_CleanOlf(hObject,eventdata)
        qans = questdlg('Do you want to clean olfactometer?',...
            'Clean olfactometer?',...
            'Yes','No','Stop','No');
        
        switch qans
            case 'Yes'
                handles.clean = true;
                while handles.clean
                    for n = 0:7
                        Write(handles.olf,'b3v',n);
                        set(handles.hText4,'String',strcat('CurrentValve=Bank3-',num2str(n)));
                        pause(3);
                        if ~handles.clean
                            return
                        end
                    end
                end
            otherwise
                handles.clean = false;
                return
        end
    end

    function Callback_hPush_RandDir(hObject,eventdata)
        % Make randomized trial directory.
        prompt = {'How many odors?','How many trials each?'};
        defAns = {'7','10'};
        x = inputdlg(prompt,'#Odors x trials',1,defAns);
        savedirectory = uigetdir(pwd,'Save path?');
        cd(savedirectory);
        NTrial = str2double(x{2});
        NOdor = str2double(x{1});
        prompt2 = arrayfun(@(a)['Odor ',num2str(a),'?'],1:NOdor,'uni',false);
        OdorName = inputdlg(prompt2,'Odor names?');
        order = [];
        for n = 1:NTrial
            order = [order,randperm(NOdor)];
        end

        for n = 1:NTrial*NOdor
            if n<10
                dirname = strcat('0',num2str(n),'-',num2str(order(n)),'-',OdorName{order(n)});
            else
                dirname = strcat(num2str(n),'-',num2str(order(n)),'-',OdorName{order(n)});
            end
            mkdir(dirname);
        end
        
    end

    function Callback_hToggle(hObject,eventdata)
        % Change color when pushed in or out.
        if isequal(get(hObject,'Value'),1)
            set(hObject,'BackgroundColor','r');
            set(hObject,'ForegroundColor','w');
            set(hObject,'String','Odor+ShockON!');
        else
            set(hObject,'BackgroundColor',[0.8314 0.8157 0.7843]);
            set(hObject,'ForegroundColor','k');
            set(hObject,'String','Odor+Shock?');
        end
        
    end

end
