function StimGUI_KS

handles.DAQ = digitalio('mcc',0);
handles.lines = addline(handles.DAQ,0:2,'out');

handles.Fig = figure;
% handles.Popup = uicontrol(handles.Fig,...
%     'Style','popup',...
%     'Units','normalized',...
%     'Position',[0.3 0.7 0.4 0.1],...
%     'String',{'V-pulse','I-pulse'},...
%     'Callback',{@Callback_popup});
handles.Push = uicontrol(handles.Fig,...
    'Style','push',...
    'Units','normalized',...
    'Position',[0.3 0.6 0.6 0.2],...
    'String','Start (Imaging and Stim with Specified Delay)',...
    'Callback',{@Callback_push});
handles.Edit1 = uicontrol(handles.Fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.3 0.2 0.2 0.1],...
    'String','3');
handles.Text1 = uicontrol(handles.Fig,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.5 0.2 0.2 0.1],...
    'String','seconds delay (both boxes)');
handles.Edit2 = uicontrol(handles.Fig,...
    'Style','edit',...
    'Units','normalized',...
    'Position',[0.3 0.1 0.2 0.1],...
    'String','1');
handles.Text2 = uicontrol(handles.Fig,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.5 0.1 0.2 0.1],...
    'String','seconds stim for WPI Box');

handles.baseval = [0 0 0];
handles.imtrig = [1 0 0];
handles.stimtrig = [0 0 1];

%     function Callback_popup(hObj,eventdata)
%         val = get(hObj,'Value');
%         if val == 1
%             disp('Vp')
%         elseif val == 2
%             disp('Ip')
%         end
%     end

    function Callback_push(hObj,eventdata)
        delay = str2double(get(handles.Edit1,'String'));
        stim = str2double(get(handles.Edit2,'String'));
        
        putvalue(handles.DAQ,handles.imtrig);
        pause(delay);
        putvalue(handles.DAQ,handles.stimtrig);
        pause(stim);
        putvalue(handles.DAQ,handles.baseval);
        
    end


end
